### ISSUE TITLE
PennCNV used to be a module on p33 - now it is gone. 

### ISSUE THREAD

**Issue by idaElken** [norment/tsd_issues#47] opened 2020-11-11 15:01 UTC
Hi, 

I have used penncnv/1.0.4 on p33 and now need to use it again both on p33 and p697. However, when trying to load it, apparently it disappeared. I imagine it was removed in an upgrade (?) since I'm the only one who used it in the past :-P

Best wishes, 
Ida

**Comment by ofrei** [comment] 2020-11-11 15:52
@idaElken Is this the right package:  https://github.com/WGLab/PennCNV ?

Do you need a specific version, i.e. 1.0.5? (as mentioned here in the instructions http://penncnv.openbioinformatics.org/en/latest/user-guide/install/ )?

**Comment by ofrei** [comment] 2020-11-11 15:57
I found pennCNV on this list:
https://www.uio.no/tjenester/it/forskning/aktuelt/abel-newsletter-1-2018.html
It would be interesting to see if other software from this list is also no longer available.

**Comment by idaElken** [comment] 2020-11-11 16:14
> @idaElken Is this the right package: https://github.com/WGLab/PennCNV ?
> 
> Do you need a specific version, i.e. 1.0.5? (as mentioned here in the instructions http://penncnv.openbioinformatics.org/en/latest/user-guide/install/ )?

Absolutely correct. 

As far as I can tell, this update does not change the actual algorithms (from 1.0.4 that I used before) but is simply to simplify installation/improve error messages (https://github.com/WGLab/PennCNV/releases), so 1.0.5 seems to be absolutely fine. 

Alex' three suggestions for options:
(1) Sandeep and/or me help you directly, i.e. by making a singularity container that runs penncnv
(2) We reach out to Sabry at TSD and he helps as part of AUS (Advanced Users Support)
(3) We make a request for installing additional software on Colossus. This is reasonable as they've had it previously , but now it's gone. Yet I think it's not many users who need PennCNV, so if we can easily solve it ourself then I wouldn't bother TSD with this question.

This may be helpful (?) if we end up installing ourselves (yourselves ;-)  ): 
20160805: PennCNV has been dockerized by Roman Hillje at the University of Zurich, Switzerland. The docker image and related documentation are available at https://hub.docker.com/r/romanhaa/penncnv/. (?)

Let me know if you want me to reach out to Sabry or how we should do it?

**Comment by ofrei** [comment] 2020-11-11 19:06
@idaElken Thank you for pointing out to the Docker image by Roman Hillje. I've converted it to singularity container by running 
 ``singularity build penncnv.sif docker://romanhaa/penncnv`` (locally on my ubuntu laptop) and imported this container to p697 project into ``/cluster/projects/p697/ofrei/comorment/`` . Could you try it out?  If you are not quite familiar with  with Singularity, here are "getting started" instructions : https://github.com/comorment/demo .

I couldn't run examples provided by PennCNV because singularity container is read-only. This is actually different from a docker container, which is writable. There are options to make a writable singularity container (`persistent overlays` and `writable images` , see links  [here](https://github.com/hpcng/singularity/issues/1254) ) - but both require ``sudo``, it seem we can't use them. Either way here is an error I get: ![image](https://user-images.githubusercontent.com/13171449/98853065-e0131100-2458-11eb-8d70-40c1bbba5bfa.png)


 I hope the above problem is specific to the PennCNV exmaple (``runex.pl``), and the actual PennCNV software might still work if PennCNV software tries to write outside of the container.

**Comment by ofrei** [comment] 2020-11-11 19:30
Hey, it's a success (thanks to https://github.com/hpcng/singularity/issues/1790 ).  Here is what I did:
```
cd /cluster/projects/p697/ofrei/comorment
singularity build --sandbox new.simg penncnv.sif
singulairty shell --no-home --writable new.simg
# now running commands within singularity container:
cd /opt/PennCNV-1.0.5/example/
perl runex.pl 1
```

![image](https://user-images.githubusercontent.com/13171449/98855677-afcd7180-245c-11eb-9d66-fee4b476d6ab.png)

**Comment by idaElken** [comment] 2020-11-11 20:11
> Hey, it's a success (thanks to [hpcng/singularity#1790](https://github.com/hpcng/singularity/issues/1790) ). Here is what I did:
> 
> ```
> cd /cluster/projects/p697/ofrei/comorment
> singularity build --sandbox new.simg penncnv.sif
> singulairty shell --no-home --writable new.simg
> # now running commands within singularity container:
> cd /opt/PennCNV-1.0.5/example/
> perl runex.pl 1
> ```
> 
> ![image](https://user-images.githubusercontent.com/13171449/98855677-afcd7180-245c-11eb-9d66-fee4b476d6ab.png)

That's fantastic news - thank you so much! I won't be able to test it further until (at earliest) Friday I'm afraid. But thank you looking forward to it!

/Ida

**Comment by ofrei** [comment] 2020-11-11 20:55
From https://hub.docker.com/r/romanhaa/penncnv/ :
>Note: To keep the image size small, it doesn't contain any R (which means visualize_cnv.pl won't be able to export jpegs).

@idaElken is this a problem?

**Comment by idaElken** [comment] 2020-11-11 21:05
Thanks for letting me know! 
No, this is not an issue since I usually use an Rpackage called iPsychCNV to visualize the CNVs with - it is much more convenient. I need to import this package to p697 (imported to p33 ages ago - if I run into issues  I'm likely to ask you and Sandeep (be warned!)

**Comment by idaElken** [comment] 2020-11-18 08:51
Hi,
Does each person need to install the container themselves?

-cause currently I don't find this folder:
/opt/PennCNV-1.0.5/example/
neither: /opt/PennCNV-1.0.5/, only /opt/

But if I try to run:
singularity build --sandbox new.simg penncnv.sif
it says "build target already exists" (?)

/Ida

**Comment by ofrei** [comment] 2020-11-18 09:09
@idaElken could you try to skip ``singularity build --sandbox new.simg penncnv.sif`` command, and run continue with these?
```
singulairty shell --no-home --writable new.simg
# now running commands within singularity container:
cd /opt/PennCNV-1.0.5/example/
perl runex.pl 1
```

The ``build target already exists`` error is because ``singularity build --sandbox new.simg penncnv.sif`` command tries to generate ``new.simg`` file which already exist. You may either change the name (i.e. use ``singularity build --sandbox penncnv_ida.simg penncnv.sif``, or simply re-use my container called ``new.simg``.

**Comment by idaElken** [comment] 2020-11-18 09:34
This is what I tried:
<img width="670" alt="Screen Shot 2020-11-18 at 10 33 29" src="https://user-images.githubusercontent.com/4227962/99512312-94e18c80-2989-11eb-86ee-fd7d6319dad0.png">

**Comment by ofrei** [comment] 2020-11-18 12:36
(to keep his up  to date - the problem is solved by "module purge" and using singularity from /bin folder)

**Comment by ofrei** [comment] 2021-04-26 09:00
@idaElken It seem we solved this with singularity - closing the ticket now.

**Closed as completed by ofrei** 2021-04-26 09:00 UTC
Labels: new software
